<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>pycharm on DebugTalk</title><link>https://debugtalk.github.io/tags/pycharm/</link><description>Recent content in pycharm on DebugTalk</description><generator>Hugo -- gohugo.io</generator><language>zh-cn</language><lastBuildDate>Mon, 13 Jul 2015 00:00:00 +0000</lastBuildDate><atom:link href="https://debugtalk.github.io/tags/pycharm/index.xml" rel="self" type="application/rss+xml"/><item><title>利用 PyCharm 进行 Python 远程调试</title><link>https://debugtalk.github.io/post/remote-debugging-with-pycharm/</link><pubDate>Mon, 13 Jul 2015 00:00:00 +0000</pubDate><guid>https://debugtalk.github.io/post/remote-debugging-with-pycharm/</guid><description>背景描述 有时候Python应用的代码在本地开发环境运行十分正常，但是放到线上以后却出现了莫名其妙的异常，经过再三排查以后还是找不到问题原因，</description></item></channel></rss>